name: DarkEnde
version: '1.0.0'
main: com.denny.darkende.DarkEnde
author: Denny
description: Einfaches EnderChest Plugin mit 3 Stufen und Anti-Dupe Schutz
commands:
  endrang:
    description: Einstellen der EnderChest Stufe für einen Spieler
    usage: /endrang <spieler> <stufe (1-3)>
    permission: darkende.admin
permissions:
  darkende.admin:
    description: Erlaubt das Einstellen der EnderChest Stufen
    default: op
  darkende.use:
    description: Erlaubt die Nutzung der erweiterten EnderChest
    default: true
